import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_connect/http/src/utils/utils.dart';
import 'package:momo/core/util/constants/constants.dart';
import 'package:momo/core/util/constants/text_style.dart';
import 'package:momo/test.dart';

class FaqScreen extends StatefulWidget {
  const FaqScreen({super.key});

  @override
  State<FaqScreen> createState() => _FaqScreenState();
}

class _FaqScreenState extends State<FaqScreen> {
  List<Map<String, dynamic>> questionList = [
    {
      Constants.question: "how long are my photo stored on your server?",
      Constants.ans:
          "At our company, we prioritize data protection and privacy as core values. As such, we have implemented advanced encryption techniques and follow current security guidelines to ensure the highest level of security at all times. In regards to the images that you upload to our app to generate AI avatars, we automatically delete them from our servers after a period of 2 days. On the other hand, the images generated by the app from the photos you uploaded will be deleted from our servers after 30 days. Please be assured that we take the necessary precautions to protect your data and uphold our commitment to privacy.",
    },
    {
      Constants.question:
          "I can't see the AI Art section and the custom prompts anymore",
      Constants.ans:
          "This might be due to a temporary glitch or an update. Please try refreshing the app or reinstalling it. If the issue persists, contact support.",
    },
    {
      Constants.question: "I'm facing an error message",
      Constants.ans:
          "Please provide more details about the error message. You can screenshot it and send it to our support team for assistance.",
    },
    {
      Constants.question: "I'm facing an error message",
      Constants.ans:
          "Please provide more details about the error message. You can screenshot it and send it to our support team for assistance.",
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: Text("FAQ"),
      ),
      body: Column(
        children: [
          Divider(height: 1, color: Colors.grey),
          SizedBox(height: 40),
          Expanded(
            child: ListView.builder(
              itemCount: questionList.length,
              itemBuilder: (context, index) {
                bool showAns = false;
                return StatefulBuilder(
                  builder: (context, setLocalState) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(vertical: 5),
                      child: Column(
                        children: [
                          Card(
                            color: Colors.blueGrey.withAlpha(100),
                            child: ListTile(
                              title: Text(
                                questionList[index][Constants.question],
                                style: getSubtitleStyle().copyWith(
                                  color: Colors.white,
                                  fontSize: 16,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              trailing: Icon(
                                showAns ? Icons.expand_less : Icons.expand_more,
                                color: Colors.white,
                              ),
                              onTap: () {
                                setLocalState(() {
                                  showAns = !showAns;
                                });
                              },
                            ),
                          ),
                          AnimatedSize(
                            duration: Duration(milliseconds: 500),
                            curve: Curves.easeInOut,
                            child: showAns
                                ? Padding(
                                    padding: const EdgeInsets.all(12.0),
                                    child: Text(
                                      questionList[index][Constants.ans],
                                      style: getSubtitleStyle().copyWith(
                                        color: Colors.white70,
                                      ),
                                    ),
                                  )
                                : SizedBox.shrink(),
                          ),
                        ],
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
